version: '3.8'

services:
  db:
    image: postgres:15
    container_name: homestay_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homestay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - homestay_net

volumes:
  postgres_data:

networks:
  homestay_net:
